- README.md
- docs/reference/config.md
- docs/reference/install-location.md
- docs/reference/install.md
- docs/reference/lazy-install.md
- docs/reference/registry-config.md
- docs/reference/registry.md
- docs/reference/usage.md
- docs/renovate.md
- docs/tutorial-basics/change-version-per-project.md
- docs/tutorial-basics/global-config.md
- docs/tutorial-basics/quick-start.md
- docs/tutorial-extras/team-config.md
- docusaurus.config.js
- src/components/HomepageFeatures.js
The repositories were transferred.
> fix: rename GitHub Owner

- docs/tutorial-basics/quick-start.md
- docusaurus.config.js
> feat: add install in header

- docusaurus.config.js
Close #12
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#configuration
> fix: fix editUrl

- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/pull/438 https://github.com/aquaproj/aqua/pull/439
> feat: add supported_if

- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/pull/444
> feat: add `rosetta2`

- docs/tutorial-extras/use-aqua-with-other-tools.md
https://github.com/aquaproj/aqua-registry/issues/1436
> fix: replace `nodejs/node` to `hashicorp/waypoint`

- docs/reference/config.md
- docs/reference/lazy-install.md
- docs/tutorial-basics/quick-start.md
- docs/tutorial-extras/add-registry.md
https://github.com/aquaproj/aqua/pull/520 https://github.com/aquaproj/aqua/pull/521
> fix: remove `inline_registry`

- docs/reference/config.md
- docs/tutorial-basics/global-config.md
https://github.com/aquaproj/aqua/pull/609
https://github.com/aquaproj/aqua/pull/610
> feat: follow up aquaproj/aqua#610

- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/issues/607
> feat: overrides

- docs/reference/config.md
- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/issues/623
> feat: add JSON Schema

- docs/reference/change-os-arch-for-test.md
https://github.com/aquaproj/aqua/pull/643
https://github.com/aquaproj/aqua/pull/644
> feat: change GOOS and GOARCH for testing Registry

- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/pull/674
> feat: support aliases

- docs/reference/config.md
- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/releases/tag/v1.7.0
> feat: add package type go

- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/releases/tag/v1.8.0
https://github.com/aquaproj/aqua/pull/811
> feat: version_source

- blog/2021-09-08-introduction.md
- blog/2021-12-04-aqua-overview.md
- blog/authors.yml
- blog/why-i-use-aqua.md
- docs/slide-blog.md
- docusaurus.config.js
https://docusaurus.io/docs/blog
> feat: enable blog and add blog links

- docs/reference/registry-config.md
https://github.com/aquaproj/aqua/pull/826
> feat: add go_install package

- docs/reference/config.md
- docs/reference/experimental-feature.md
- docs/reference/registry-config/go-package.md
https://docusaurus.io/docs/markdown-features/admonitions
> feat: use adomonition

- docs/reference/usage.md
- scripts/generate-usage.sh
https://github.com/aquaproj/aqua/releases/tag/v1.11.0
https://github.com/aquaproj/aqua/issues/856
> docs: update usage

- docs/reference/shell-completion.md
https://github.com/aquaproj/aqua/issues/856
> feat: shell completion

- docs/reference/config.md
- docs/reference/registry-config/complete-windows-exe.md
- docs/reference/registry-config/index.md
- docs/reference/registry-config/supported-envs.md
- docs/reference/registry-config/supported-if.md
- docs/reference/windows-support.md
> feat: update Windows Support

- docs/reference/registry-style-guide.md
- docs/reference/scaffold-registry.md
- docs/reference/windows-support.md
- docs/tutorial-extras/add-registry.md
- docs/tutorial-extras/renovate.md
https://github.com/aquaproj/aqua/issues/995
> feat: add the registry style guide

- docs/tutorial-basics/quick-start.md
* https://twitter.com/toro_00/status/1552133931407126528
* https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html
Thank you, Katacoda.
> fix: remove katacoda

- docs/reference/checksum.md
ref. https://github.com/aquaproj/aqua/releases/tag/v1.19.4
> chore: Added supported algorithm

- docs/reference/checksum.md
- docs/slide-blog.md
https://zenn.dev/shunsuke_suzuki/articles/aqua-checksum-verification
> add links to blog post

- docs/demo.mdx
- package.json
- src/css/custom.css
- src/pages/index.js
- yarn.lock
- https://github.com/aquaproj/aquaproj.github.io/pull/91
> fix: remove youtube

- docs/reference/codes/002.md
- docs/tutorial-extras/policy-as-code.md
- https://github.com/aquaproj/aqua/issues/1306
> add policy as code

- docs/slide-blog.md
- docusaurus.config.js
https://zenn.dev/shunsuke_suzuki/articles/aqua-policy-as-code
> add a link to blog post

- docs/reference/registry-style-guide.md
I read [oss-contribution-guide](https://github.com/suzuki-shunsuke/oss-contribution-guide).
[It says that "typo fixes" don't need to create a issue](https://github.com/suzuki-shunsuke/oss-contribution-guide#create-an-issue-before-creating-a-pull-request), so I think this pull request doesn't need to create a issue either.
Thank you.
> fix: fix link

- docs/comparison/apt-yum.md
- docs/comparison/arkade.md
- docs/comparison/asdf.md
- docs/comparison/common.md
- docs/comparison/index.md
- docs/comparison/marcosnils-bin.md
- docs/overview.md
- docs/reference/config.md
- docs/reference/registry-config/aliases.md
- docs/reference/registry-config/index.md
- docs/reference/registry-config/supported-if.md
- docs/reference/scaffold-registry.md
- docs/reference/shell-completion.md
- docs/tutorial-basics/install-only-link.md
- docs/tutorial-extras/add-registry.md
- docs/tutorial-extras/policy-as-code.md
- docs/tutorial-extras/private-package.md
- docs/tutorial-extras/team-config.md
https://github.com/aquaproj/aquaproj.github.io/pull/231#issuecomment-1368441644
> fix: change relative URLs to relative file paths

- docs/reference/registry-config/template.md
- docs/reference/registry-config/version-filter.md
- docs/reference/registry-config/version-overrides.md
- docs/reference/registry-config/version-prefix.md
- https://github.com/aquaproj/aqua/issues/1545
> add document about version_prefix

- docs/reference/config.md
- docs/tutorial-extras/keep-in-one-dir.md
- https://github.com/aquaproj/aqua/issues/1595
> update aqua configuration file paths

- .github/workflows/test.yaml
- https://github.com/aquaproj/aquaproj.github.io/issues/314
> ci: run typos

- .github/workflows/test.yaml
- https://github.com/aquaproj/aquaproj.github.io/pull/319
> ci: fix path filters

- docs/reference/config/index.md
- docs/reference/security/policy-as-code.md
- docs/reference/upgrade-guide/v2/only-standard-registry-is-allowed-by-default.md
- https://github.com/aquaproj/aqua/issues/1790
> AQUA_DISABLE_POLICY

- docs/index.md
- docusaurus.config.js
- https://github.com/aquaproj/aqua/issues/1930
> link discussions

- docs/reference/config/index.md
- docs/reference/execve-2.md
- https://github.com/aquaproj/aqua/issues/1925
> add execve-2

- docs/reference/registry-config/cargo-package.md
- docs/reference/registry-config/index.md
https://github.com/orgs/aquaproj/discussions/2016
> add a new package type `cargo`

- docs/reference/codes/005.md
- docs/reference/registry-config/cargo-package.md
https://github.com/orgs/aquaproj/discussions/2016
> add reference for cargo install error

- docs/reference/codes/006.md
- docs/reference/config/index.md
- docs/reference/lazy-install.md
- https://github.com/orgs/aquaproj/discussions/2058
> disable lazy install

- docs/index.md
- docs/reference/slide-blog.md
https://zenn.dev/shunsuke_suzuki/books/aqua-handbook
> add links to e-book

- docs/index.md
https://discord.com/channels/1141777454164365382/1162444533959757955
> add a link to discord

- docs/products/aqua-renovate-config.md
- https://github.com/aquaproj/aqua-renovate-config/pull/449
> add aqua-renovate-config preset

- docs/reference/registry-config/index.md
- docs/reference/registry-config/windows_arm_emulation.md
- docs/reference/windows-support.md
- https://github.com/orgs/aquaproj/discussions/2514
> add windows_arm_emulation

- docs/reference/slide-blog.md
Hi @suzuki-shunsuke, thank you for development a great tool!
I fixed a typo and added a slide that I talked at [Engineering Productivity Meetup](https://cybozu.connpass.com/event/298452/).
> chore: added a new slide and fixed a typo

- docs/reference/security/cosign-slsa.md
[#2631](https://github.com/orgs/aquaproj/discussions/2631) [#2633](https://github.com/aquaproj/aqua/pull/2633) [#2634](https://github.com/aquaproj/aqua/pull/2634)
> support disabling cosign and slsa

- docs/guides/build-container-image.md
- https://github.com/aquaproj/aquaproj.github.io/pull/905
--
- Change the base image from alpine to debian
- Verify the checksum of aqua-installer
- Use checksum verification
- Stop aqua-installer's deprecated option `-i`
> fix: update build-container-image

- docs/products/aqua-registry/contributing.md
> add cmdx s

- docs/reference/config/shell-completion.md
- docs/reference/usage.md
- https://github.com/aquaproj/aqua/pull/2929
> fish completion

- docs/guides/renovate.md
The deleted sentence is no longer true: `aqua update` exists.
> fix(docs): Remove claim that aqua does not update packages

- docs/install.md
- docs/reference/execve-2.md
- docs/reference/lazy-install.md
- docs/reference/usage.md
- docs/reference/windows-support.md
- docs/trouble-shooting.md
- https://github.com/aquaproj/aqua/issues/2918
- https://github.com/aquaproj/aqua/pull/3005
> use hard links on Windows

- docs/reference/nodejs-support.md
- docusaurus.config.js
- https://github.com/aquaproj/aqua/issues/2996
> Node.js Support

- docs/reference/nodejs-support.md
- https://github.com/aquaproj/aqua/issues/2996#issuecomment-2308336594
> fix: fix PATH on Windows

- docs/index.md
- docs/reference/registry-config/index.md
- docs/reference/registry-config/minisign.md
- docs/reference/restriction.md
- docs/reference/security/index.md
- docs/reference/security/minisign.md
- src/components/HomepageFeatures.js
- https://github.com/aquaproj/aqua/pull/3103
> add document about minisign

- docs/install.md
- docs/reference/config/index.md
- docs/reference/registry-config/github-artifact-attestations.md
- docs/reference/registry-config/index.md
- docs/reference/security/cosign-slsa.md
- docs/reference/security/github-artifact-attestations.md
- docs/reference/security/index.md
- docs/reference/security/minisign.md
- src/components/HomepageFeatures.js
- https://github.com/aquaproj/aqua/pull/3131
- https://github.com/aquaproj/aqua/issues/3117
- https://github.com/aquaproj/aqua/pull/3119
> add the document about GitHub Artifact Attestations

- docs/products/aqua-registry/contributing.md
I found the closing brace missing in the documentation.
> Fix a typo of contributing.md

- src/components/HomepageFeatures.js
- [ x] Read [OSS Contribution Guide](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/README.md)
- [ x] [All commits are signed](https://github.com/suzuki-shunsuke/oss-contribution-guide/blob/main/docs/commit-signing.md)
- [ x] [Avoid force push](https://github.com/suzuki-shunsuke/oss-contribution-guide?tab=readme-ov-file#dont-do-force-pushes-after-opening-pull-requests)
- [ x] Do only one thing in one Pull Request
fixes #1142
> fixes typo on homepage

- docs/reference/config/shell-completion.md
Change `fish.zsh` to match the instructions that follow
> Update shell-completion.md - edit fish completion file path

- docs/reference/config/command-alias.md
- docs/reference/config/index.md
- https://github.com/aquaproj/aqua/pull/3224
> command aliases

- docs/reference/security/policy-as-code/index.md
- https://github.com/aquaproj/aqua/issues/3202
> docs: add a link to JSON Schema of policy files

- docs/reference/config/index.md
- docs/reference/config/version-expr.md
- https://github.com/aquaproj/aqua/pull/3363
> version-expr

- docs/guides/build-container-image.md
- docs/guides/policy-as-code.md
- docs/guides/wrap-aqua-with-task-runner.md
- docs/install.md
- docs/products/aqua-installer/index.md
- docs/products/aqua-renovate-config.md
- docs/reference/codes/006.md
- docs/reference/security/cosign-slsa.md
- docs/tutorial/index.md
- https://github.com/aquaproj/aqua-installer/issues/753
> chore: update aqua-installer

- docs/guides/index.md
- docs/guides/uninstall-packages.md
- docs/guides/vacuum.md
- https://github.com/aquaproj/aqua/pull/3467
> feat: vacuum

- docs/reference/registry-config/files.md
- https://github.com/aquaproj/aqua/issues/3130#issuecomment-2661230756
> add the description of .files[].link

- blog/2021-12-23-why-i-use-aqua.md
- docs/reference/registry.md
- docs/reference/usage.md
> docs: grammar fixes

- docs/reference/security/cosign-slsa.md
Refs https://github.com/aquaproj/aqua-registry/pull/32051#issuecomment-2660476177
> docs(cosign-slsa): fix slsa-verifier install info

- docs/reference/restriction.md
> docs(restriction): note gh install as exception

- docs/develop-registry/index.md
> docs: fix typo

- .github/workflows/autofix.yaml
- docs/guides/checksum.md
- https://github.com/suzuki-shunsuke/batch-task/issues/8
> ci: Replace autofix-ci/action with suzuki-shunsuke/autofix-ci-action

- docs/reference/registry-config/cosign.md
> fix: remove cosign_experimental

- docs/index.md
> fix: formerly X to formerly Twitter

- docs/reference/config/index.md
- docs/reference/security/index.md
- docs/reference/security/keyring.md
- https://github.com/aquaproj/aqua/pull/3852
> Add keyring

- .github/workflows/actionlint.yaml
- .github/workflows/test.yaml
- docs/guides/checksum.md
- https://github.com/suzuki-shunsuke/batch-task/issues/14
> ci: Fix if: failure() of GitHub Actions
